### ISSUE TITLE
Décider de l'implémentation système de l'outil PDF parser

### ISSUE THREAD

**Issue by PaulGalloFR** [Floliroy/PDF-Parser#2]
boiiiiiii on fait des vm ou des conteneurs? Linux ou windows(non)? Environnement réseau?

**Comment by Floliroy** [comment]
Sachant que c'est du node et que c'est aussi un bot discord, on le fait just tourner sur un linux en tache de fond (genre sur un tmux) et voila.

On peut aussi l'heberger sur heroku gratuitement (mais moi je peux pas j'ai deja mon bot dessus), ca fonctionne vraiment pas mal.

**Comment by PaulGalloFR** [comment]
Problème avec ces solutions c'est qu'on est en dehors de l'infra STRI, je filerais bien un coup de fil a Latu, je suis sur qu'il a des VM a nous prêter. Tu veut absolument garder la main sur l'infra?

**Comment by Floliroy** [comment]
Si possible ouai ca permet d'avoir des fix plus rapide, après en soit si on le fait tourner sur un linux intra a la fac why not hein tant que j'ai une connexion ssh dessus.

Mais pour le coup heroku je pense c'est vraiment la meilleur solution.

**Comment by PaulGalloFR** [comment]
Bon on vois pour la récup du pdf et si c'est nécessaire on demandera a Latu
